version: '3'

services:
  app:
    build: 
      dockerfile: dockerfile
    image: napatsorn/app:1.0.0
    container_name: My-app
    ports:
     - 1337:1337
    environment:
     - DATABASE_CLIENT=${DATABASE_CLIENT}
     - DATABASE_HOST=db
     - DATABASE_PORT=${DATABASE_PORT}
     - DATABASE_NAME=${DATABASE_NAME}
     - DATABASE_USERNAME=${DATABASE_USERNAME}
     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
     - DATABASE_SSL=${DATABASE_SSL}
    networks:
      - nuey
  db:
    image: postgres:latest
    container_name: My-db
    ports:
     - ${DATABASE_PORT}:5432
    environment:
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     - POSTGRES_USER=${DATABASE_USERNAME}
     - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - nuey

networks:
  nuey:

